import './_global'
import './components/hero';
import './components/slider/slider-locations';
import './components/slider/slider-reviews';
import './components/faq-content';
import './components/textarea-auto-resize';
import './components/camp-popup';
import './components/banner-certificate';
import './components/slider/team-slider';
